### PR TITLE
fix: remove unexpected settings

### PR DESCRIPTION
**Pull request by xieve**
I've not tested this; in particular, it's very possible that things might break when `&textwidth` is set to 0 (default).

### CODE REVIEW

**Comment by xieve** [comment]
Closes #1

**Comment by Konfekt** [comment]
> things might break when &textwidth is set to 0 

Good catch; now that you're roped in and have the PR open, would you mind replacing these occurrences

```vim
' --set code_width=' . &textwidth
```

with

```vim
(&textwidth > 0 ? ' --set code_width=' . &textwidth : '')
```

?

**Comment by xieve** [comment]
Done :)
One more thing: I've noticed that for quite a few formatters, if `expandtabs` is unset, both the option for hard tabs and the print width is set. I feel like it should probably be one or the other, right?

**Comment by Konfekt** [comment]
Thank you!

>  I feel like it should probably be one or the other, right?

That would be cleaner, yes. If the command does not complain, I wouldn't go to too great lengths about it, though. 

In any event, thank you for the amendment to `shellfmt` regarding this setting.

**Comment by Konfekt** [comment]
Further refinements are very much appreciated, in any events

**Comment by Konfekt** [comment]
@xieve Would you like to expand this PR on `expandtabs`?

**Pull request merged**
